[workspace]
members = [
    "chir-rs",
    "chir-rs-castore",
    "chir-rs-client",
    "chir-rs-config",
    "chir-rs-db",
    "chir-rs-fe",
    "chir-rs-gemini",
    "chir-rs-http",
    "chir-rs-http-api",
    "chir-rs-misc",
]
resolver = "2"
