-- Add migration script here
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_running BOOLEAN NOT NULL DEFAULT 'f',
    retries BIGINT NOT NULL DEFAULT 0,
    run_after TIMESTAMP WITH TIME ZONE NOT NULL,
    job_data BYTEA NOT NULL,
    priority BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE,
    version INT NOT NULL

);
CREATE INDEX jobs_running ON jobs (is_running);
CREATE INDEX jobs_run_after ON jobs (run_after);
CREATE INDEX jobs_priority ON jobs(priority);
CREATE INDEX jobs_priority_run_after_running ON jobs (priority DESC, run_after ASC, is_running);
CREATE INDEX jobs_last_updated ON jobs (updated_at, is_running);